name: Maven Central Relase
on: workflow_dispatch

env:
  MAVEN_CLI: -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
          server-id: ossrh
          server-username: OSSRH_TOKEN_USERNAME
          server-password: OSSRH_TOKEN_PASSWORD
          gpg-private-key: ${{ secrets.JAVA_NATIVE_PGP_KEY }}
          gpg-passphrase: PGP_KEY_PASSPHRASE
      - name: Prep Maven Repo
        run: mvn ${MAVEN_CLI} dependency:resolve-plugins dependency:resolve
      - name: Publish artifacts to Maven Central
        run: mvn ${MAVEN_CLI} clean deploy -P package,maven-central-release
        env:
          OSSRH_TOKEN_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          OSSRH_TOKEN_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
          PGP_KEY_PASSPHRASE: ${{ secrets.JAVA_NATIVE_PGP_KEY_PASSPHRASE }}
