include(DetectLinux)

set(CMAKE_SYSTEM_NAME Linux)
set(TOOLCHAIN_PREFIX arm-linux-gnueabi)

# Since Trusty, append compiler version
if(UBUNTU AND LINUX_VERSION VERSION_GREATER "16.04")
	set(COMPILER_VERSION 5)
	if(NOT COMPILER_VERSION MATCHES "-.*")
		set(COMPILER_VERSION "-${COMPILER_VERSION}")
	endif()
endif()

set(TOOLCHAIN_SUFFIX hf)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}${TOOLCHAIN_SUFFIX}-gcc${COMPILER_VERSION})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}${TOOLCHAIN_SUFFIX}-g++${COMPILER_VERSION})
set(CMAKE_STRIP ${TOOLCHAIN_PREFIX}${TOOLCHAIN_SUFFIX}-strip CACHE FILEPATH "" FORCE)
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX}${TOOLCHAIN_SUFFIX}/)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)

