# Parse /etc/os-release for Linux version information
if(EXISTS /etc/os-release)
    file(STRINGS /etc/os-release LINUX_NAME LIMIT_COUNT 1 REGEX "^ID=")
    file(STRINGS /etc/os-release LINUX_VERSION LIMIT_COUNT 1 REGEX "^VERSION_ID=")
    string(REPLACE "\"" "" LINUX_NAME "${LINUX_NAME}")
    string(REPLACE "\"" "" LINUX_VERSION "${LINUX_VERSION}")
    string(REGEX REPLACE ".*=" "" LINUX_NAME "${LINUX_NAME}")
    string(REGEX REPLACE ".*=" "" LINUX_VERSION "${LINUX_VERSION}")
endif()

message(STATUS "Linux Name: ${LINUX_NAME}")
message(STATUS "Linux Version: ${LINUX_VERSION}")

if(LINUX_NAME STREQUAL "ubuntu")
    set(UBUNTU true)
elseif(LINUX_NAME STREQUAL "fedora")
    set(FEDORA true)
elseif(LINUX_NAME STREQUAL "debian")
    set(DEBIAN true)
elseif(LINUX_NAME MATCHES "arch|manjaro")
    set(ARCHLINUX true)
endif()
